BTCUSDT = "BTCUSDT"
ETHUSDT = "ETHUSDT"
ETHBTC = "ETHBTC"

PAIRS_CRIPTO = [BTCUSDT, ETHUSDT, ETHBTC]

RIGHT_TRIANGLE_STRATEGY = "right_triangle_strategy"
LEFT_TRIANGLE_STRATEGY = "left_triangle_strategy"
